# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Wavelength_ScanjEsUCh.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_WavelengthScan(object):
    def setupUi(self, WavelengthScan):
        if not WavelengthScan.objectName():
            WavelengthScan.setObjectName(u"WavelengthScan")
        WavelengthScan.resize(964, 734)
        self.centralwidget = QWidget(WavelengthScan)
        self.centralwidget.setObjectName(u"centralwidget")
        self.start = QPushButton(self.centralwidget)
        self.start.setObjectName(u"start")
        self.start.setGeometry(QRect(620, 40, 131, 41))
        font = QFont()
        font.setPointSize(12)
        self.start.setFont(font)
        self.stop = QPushButton(self.centralwidget)
        self.stop.setObjectName(u"stop")
        self.stop.setGeometry(QRect(770, 40, 131, 41))
        self.stop.setFont(font)
        self.wavelengthScanGraph = QGraphicsView(self.centralwidget)
        self.wavelengthScanGraph.setObjectName(u"wavelengthScanGraph")
        self.wavelengthScanGraph.setGeometry(QRect(620, 150, 311, 231))
        self.timeScanGraph = QGraphicsView(self.centralwidget)
        self.timeScanGraph.setObjectName(u"timeScanGraph")
        self.timeScanGraph.setGeometry(QRect(620, 430, 311, 241))
        self.labelWavelengthScanGraph = QLabel(self.centralwidget)
        self.labelWavelengthScanGraph.setObjectName(u"labelWavelengthScanGraph")
        self.labelWavelengthScanGraph.setGeometry(QRect(620, 120, 161, 31))
        self.labelWavelengthScanGraph.setFont(font)
        self.labelTimeScanGraph = QLabel(self.centralwidget)
        self.labelTimeScanGraph.setObjectName(u"labelTimeScanGraph")
        self.labelTimeScanGraph.setGeometry(QRect(620, 400, 161, 31))
        self.labelTimeScanGraph.setFont(font)
        self.labelScanSettings = QLabel(self.centralwidget)
        self.labelScanSettings.setObjectName(u"labelScanSettings")
        self.labelScanSettings.setEnabled(True)
        self.labelScanSettings.setGeometry(QRect(250, 170, 151, 31))
        self.labelScanSettings.setFont(font)
        self.labelSetPointSettings = QLabel(self.centralwidget)
        self.labelSetPointSettings.setObjectName(u"labelSetPointSettings")
        self.labelSetPointSettings.setEnabled(True)
        self.labelSetPointSettings.setGeometry(QRect(40, 170, 171, 31))
        self.labelSetPointSettings.setFont(font)
        self.labelActualSettings = QLabel(self.centralwidget)
        self.labelActualSettings.setObjectName(u"labelActualSettings")
        self.labelActualSettings.setEnabled(True)
        self.labelActualSettings.setGeometry(QRect(450, 170, 151, 31))
        self.labelActualSettings.setFont(font)
        self.scanSettings = QSplitter(self.centralwidget)
        self.scanSettings.setObjectName(u"scanSettings")
        self.scanSettings.setGeometry(QRect(230, 210, 171, 351))
        self.scanSettings.setOrientation(Qt.Vertical)
        self.labelStartWavelength = QLabel(self.scanSettings)
        self.labelStartWavelength.setObjectName(u"labelStartWavelength")
        font1 = QFont()
        font1.setPointSize(10)
        self.labelStartWavelength.setFont(font1)
        self.scanSettings.addWidget(self.labelStartWavelength)
        self.startWavelength = QDoubleSpinBox(self.scanSettings)
        self.startWavelength.setObjectName(u"startWavelength")
        self.startWavelength.setFont(font)
        self.scanSettings.addWidget(self.startWavelength)
        self.labelStopWavelength = QLabel(self.scanSettings)
        self.labelStopWavelength.setObjectName(u"labelStopWavelength")
        self.labelStopWavelength.setFont(font1)
        self.scanSettings.addWidget(self.labelStopWavelength)
        self.stopWavelength = QDoubleSpinBox(self.scanSettings)
        self.stopWavelength.setObjectName(u"stopWavelength")
        self.stopWavelength.setFont(font)
        self.scanSettings.addWidget(self.stopWavelength)
        self.labelVelocity = QLabel(self.scanSettings)
        self.labelVelocity.setObjectName(u"labelVelocity")
        self.labelVelocity.setFont(font1)
        self.scanSettings.addWidget(self.labelVelocity)
        self.velocity = QDoubleSpinBox(self.scanSettings)
        self.velocity.setObjectName(u"velocity")
        self.velocity.setFont(font)
        self.scanSettings.addWidget(self.velocity)
        self.labelDesiredScans = QLabel(self.scanSettings)
        self.labelDesiredScans.setObjectName(u"labelDesiredScans")
        self.labelDesiredScans.setFont(font1)
        self.scanSettings.addWidget(self.labelDesiredScans)
        self.desiredScans = QSpinBox(self.scanSettings)
        self.desiredScans.setObjectName(u"desiredScans")
        self.desiredScans.setFont(font)
        self.scanSettings.addWidget(self.desiredScans)
        self.labelScansCompleted = QLabel(self.scanSettings)
        self.labelScansCompleted.setObjectName(u"labelScansCompleted")
        self.labelScansCompleted.setFont(font1)
        self.scanSettings.addWidget(self.labelScansCompleted)
        self.scansCompleted = QLCDNumber(self.scanSettings)
        self.scansCompleted.setObjectName(u"scansCompleted")
        self.scanSettings.addWidget(self.scansCompleted)
        self.splitterSetPointSettings = QSplitter(self.centralwidget)
        self.splitterSetPointSettings.setObjectName(u"splitterSetPointSettings")
        self.splitterSetPointSettings.setGeometry(QRect(40, 210, 161, 201))
        self.splitterSetPointSettings.setOrientation(Qt.Vertical)
        self.labelSetWavelength = QLabel(self.splitterSetPointSettings)
        self.labelSetWavelength.setObjectName(u"labelSetWavelength")
        self.labelSetWavelength.setFont(font1)
        self.splitterSetPointSettings.addWidget(self.labelSetWavelength)
        self.setWavelength = QDoubleSpinBox(self.splitterSetPointSettings)
        self.setWavelength.setObjectName(u"setWavelength")
        self.setWavelength.setFont(font)
        self.splitterSetPointSettings.addWidget(self.setWavelength)
        self.labelCurrent = QLabel(self.splitterSetPointSettings)
        self.labelCurrent.setObjectName(u"labelCurrent")
        self.labelCurrent.setFont(font1)
        self.splitterSetPointSettings.addWidget(self.labelCurrent)
        self.setCurrent = QDoubleSpinBox(self.splitterSetPointSettings)
        self.setCurrent.setObjectName(u"setCurrent")
        self.setCurrent.setFont(font)
        self.splitterSetPointSettings.addWidget(self.setCurrent)
        self.labelPiezoVoltage = QLabel(self.splitterSetPointSettings)
        self.labelPiezoVoltage.setObjectName(u"labelPiezoVoltage")
        self.labelPiezoVoltage.setFont(font1)
        self.splitterSetPointSettings.addWidget(self.labelPiezoVoltage)
        self.setPiezoVoltage = QDoubleSpinBox(self.splitterSetPointSettings)
        self.setPiezoVoltage.setObjectName(u"setPiezoVoltage")
        self.setPiezoVoltage.setFont(font)
        self.splitterSetPointSettings.addWidget(self.setPiezoVoltage)
        self.splitterActualValues = QSplitter(self.centralwidget)
        self.splitterActualValues.setObjectName(u"splitterActualValues")
        self.splitterActualValues.setGeometry(QRect(450, 210, 129, 141))
        self.splitterActualValues.setOrientation(Qt.Vertical)
        self.labelWavelengthValue = QLabel(self.splitterActualValues)
        self.labelWavelengthValue.setObjectName(u"labelWavelengthValue")
        self.labelWavelengthValue.setFont(font1)
        self.splitterActualValues.addWidget(self.labelWavelengthValue)
        self.wavelengthValue = QLCDNumber(self.splitterActualValues)
        self.wavelengthValue.setObjectName(u"wavelengthValue")
        self.splitterActualValues.addWidget(self.wavelengthValue)
        self.labelCurrentValue = QLabel(self.splitterActualValues)
        self.labelCurrentValue.setObjectName(u"labelCurrentValue")
        self.labelCurrentValue.setFont(font1)
        self.splitterActualValues.addWidget(self.labelCurrentValue)
        self.currentValue = QLCDNumber(self.splitterActualValues)
        self.currentValue.setObjectName(u"currentValue")
        self.splitterActualValues.addWidget(self.currentValue)
        self.desiredLaser = QListWidget(self.centralwidget)
        QListWidgetItem(self.desiredLaser)
        QListWidgetItem(self.desiredLaser)
        self.desiredLaser.setObjectName(u"desiredLaser")
        self.desiredLaser.setGeometry(QRect(40, 450, 161, 41))
        self.labelDesiredLaser = QLabel(self.centralwidget)
        self.labelDesiredLaser.setObjectName(u"labelDesiredLaser")
        self.labelDesiredLaser.setGeometry(QRect(40, 420, 121, 21))
        self.labelDesiredLaser.setFont(font1)
        WavelengthScan.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(WavelengthScan)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 964, 21))
        WavelengthScan.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(WavelengthScan)
        self.statusbar.setObjectName(u"statusbar")
        WavelengthScan.setStatusBar(self.statusbar)

        self.retranslateUi(WavelengthScan)

        QMetaObject.connectSlotsByName(WavelengthScan)
    # setupUi

    def retranslateUi(self, WavelengthScan):
        WavelengthScan.setWindowTitle(QCoreApplication.translate("WavelengthScan", u"MainWindow", None))
        self.start.setText(QCoreApplication.translate("WavelengthScan", u"Start", None))
        self.stop.setText(QCoreApplication.translate("WavelengthScan", u"Stop", None))
        self.labelWavelengthScanGraph.setText(QCoreApplication.translate("WavelengthScan", u"Wavelength Scan", None))
        self.labelTimeScanGraph.setText(QCoreApplication.translate("WavelengthScan", u"Time Scan", None))
        self.labelScanSettings.setText(QCoreApplication.translate("WavelengthScan", u"Scan Settings", None))
        self.labelSetPointSettings.setText(QCoreApplication.translate("WavelengthScan", u"Set Point Settings", None))
        self.labelActualSettings.setText(QCoreApplication.translate("WavelengthScan", u"Actual Values", None))
        self.labelStartWavelength.setText(QCoreApplication.translate("WavelengthScan", u"Start Wavelength (nm)", None))
        self.labelStopWavelength.setText(QCoreApplication.translate("WavelengthScan", u"Stop Wavelength (nm)", None))
        self.labelVelocity.setText(QCoreApplication.translate("WavelengthScan", u"Velocity (nm/s)", None))
        self.labelDesiredScans.setText(QCoreApplication.translate("WavelengthScan", u"Desired # of  Scans", None))
        self.labelScansCompleted.setText(QCoreApplication.translate("WavelengthScan", u"Scans Completed", None))
        self.labelSetWavelength.setText(QCoreApplication.translate("WavelengthScan", u"Wavelength (nm)", None))
        self.labelCurrent.setText(QCoreApplication.translate("WavelengthScan", u"Current (mA)", None))
        self.labelPiezoVoltage.setText(QCoreApplication.translate("WavelengthScan", u"Piezo Voltage (%)", None))
        self.labelWavelengthValue.setText(QCoreApplication.translate("WavelengthScan", u"Wavelength (nm)", None))
        self.labelCurrentValue.setText(QCoreApplication.translate("WavelengthScan", u"Current (mA)", None))

        __sortingEnabled = self.desiredLaser.isSortingEnabled()
        self.desiredLaser.setSortingEnabled(False)
        ___qlistwidgetitem = self.desiredLaser.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("WavelengthScan", u"6700 SN41044", None));
        ___qlistwidgetitem1 = self.desiredLaser.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("WavelengthScan", u"6700 SN18084", None));
        self.desiredLaser.setSortingEnabled(__sortingEnabled)

        self.labelDesiredLaser.setText(QCoreApplication.translate("WavelengthScan", u"Desired Laser", None))
    # retranslateUi

